#!/usr/bin/python
# coding=utf-8

"""
Задача на finally

Написать функцию, которая генерирует 3 разных вида исключений в зависимости от
переданных параметров(например: ValueError, TypeError, ZeroDivisionError). Обернуть
вызов функции в блок try .. finally. Проверить, что программа входит в блок finally с
помощью отладочного print.
Запустить программу несколько раз, проверить, что генерируются разные виды
исключений и что всегда срабатывает код в блоке finally.
"""